### ISSUE TITLE
glrsgen doesn't work on Windows

### ISSUE THREAD

**Issue by imbaczek** [rust-windowing/gl-rs#79]
```
(gdb) run --xml deps/khronos-api/gl.xml
Starting program: d:\Baczyslaw\progz\rust\piston-workspace\gl-rs/bin/glrsgen.exe --xml deps/khronos-api/gl.xml
[New Thread 6340.0x2cb8]

Program received signal SIGSEGV, Segmentation fault.
0x6805b0f6 in strsep () from C:\Program Files (x86)\Git\bin\msys-1.0.dll
(gdb) bt
#0  0x6805b0f6 in strsep () from C:\Program Files (x86)\Git\bin\msys-1.0.dll
#1  0x6802cfe9 in msys-1.0!calloc ()
   from C:\Program Files (x86)\Git\bin\msys-1.0.dll
#2  0x68094e7c in wctype () from C:\Program Files (x86)\Git\bin\msys-1.0.dll
#3  0x6802cd50 in msys-1.0!malloc ()
   from C:\Program Files (x86)\Git\bin\msys-1.0.dll
#4  0x70e6f622 in xmlNewMutex () from c:\MinGW\bin\msys-xml2-2.dll
#5  0x70e32724 in xmlInitMemory () from c:\MinGW\bin\msys-xml2-2.dll
#6  0x70e207ec in xmlInitParser () from c:\MinGW\bin\msys-xml2-2.dll
#7  0x0049984a in parse_str::closure.3746 ()
#8  0x0054662d in one::Once::doit::h714768cedc4a4b4aK9b::v0.11.0.pre ()
#9  0x004994a9 in parse_str::h2f464349d6bc4373fZa::v0.1 ()
#10 0x0040378f in registry::RegistryBuilder::parse::haae85b4af3e271b1Spa::v0.1
    ()
#11 0x0040367a in registry::Registry::from_xml::h003bee27738626d3vfa::v0.1 ()
#12 0x0044a1f3 in main::hf878778f1f103e9aUSb::v0.1 ()
#13 0x0048b938 in start::closure.7234 ()
#14 0x0054e29c in task::Task::run::closure.5416 ()
#15 0x00550595 in unwind::try::try_fn::h1fe867e1154595bbSqd::v0.11.0.pre ()
#16 0x00551c16 in rust_try ()
#17 0x00550415 in unwind::try::h07a76d9a36570aebvod::v0.11.0.pre ()
#18 0x0054e05e in task::Task::run::hce4db6be7cbaab92fTc::v0.11.0.pre ()
#19 0x0048b7c6 in start::h702fffe28bf59d87jye::v0.11.0.pre ()
#20 0x0048b661 in lang_start::h092be248edef1c25Dxe::v0.11.0.pre ()
#21 0x0044a3d0 in main ()
(gdb)
```

library versions:

libxml2-2.7.6-1-msys-1.0.13
libiconv-1.14-1-msys-1.0.17
libcharset-1.14-1-msys-1.0.17

**Comment by rpvelloso** [comment]
how did you solve this? I'm having the same problem with libxml2.

**Comment by tomaka** [comment]
@rpvelloso You probably have a wrong version of the library.
